version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = '╭─'
    template = ' {{ .Icon }} '
    foreground = '#f2f3f8'
    background = '#d75f00'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      alpine = ''
      arch = ''
      centos = ''
      debian = ''
      elementary = ''
      fedora = ''
      gentoo = ''
      linux = ''
      macos = ''
      manjaro = ''
      mint = ''
      opensuse = ''
      raspbian = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    template = ' {{ .UserName }} '
    foreground = '#4e4e4e'
    powerline_symbol = ''
    background = '#e4e4e4'
    type = 'session'
    style = 'powerline'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = '#f2f3f8'
    powerline_symbol = ''
    background = '#0087af'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      folder_icon = '…'
      folder_separator_icon = ' <transparent></> '
      max_depth = 3.0
      style = 'unique'

  [[blocks.segments]]
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <transparent></> <#121318> {{ .Working.String }}</>{{ end }}{{ if .Staging.Changed }} <transparent></> <#121318> {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }} <transparent></> <#121318> {{ .StashCount }}</>{{ end }} '
    foreground = '#f2f3f8'
    background = '#378504'
    type = 'git'
    style = 'diamond'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#a97400{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#54433a{{ end }}', '{{ if gt .Ahead 0 }}#744d89{{ end }}', '{{ if gt .Behind 0 }}#744d89{{ end }}']

    [blocks.segments.properties]
      branch_gone_icon = ''
      branch_icon = ' '
      branch_identical_icon = ''
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '  {{ .FormattedMs }} '
    foreground = '#585858'
    powerline_symbol = ''
    background = '#e4e4e4'
    type = 'executiontime'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      always_enabled = true
      style = 'austin'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ .CurrentDate | date .Format }} '
    foreground = '#f2f3f8'
    background = '#d75f00'
    type = 'time'
    style = 'diamond'
    invert_powerline = true

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─ {{ if .Root }}#{{else}}${{end}}'
    foreground = '#d75f00'
    type = 'text'
    style = 'plain'
